// <auto-generated />
using Life_foods_api_csharp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Life_foods_api_csharp.Migrations
{
    [DbContext(typeof(FoodApiContext))]
    [Migration("20211019182254_create-foodingredient")]
    partial class createfoodingredient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Life_foods_api_csharp.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Carbs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Energy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fats")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Proteins")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("FoodId");

                    b.HasAlternateKey("Name");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Life_foods_api_csharp.Models.FoodIngredient", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("FoodId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("FoodIngredients");
                });

            modelBuilder.Entity("Life_foods_api_csharp.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IngredientId");

                    b.HasAlternateKey("IngredientName");

                    b.ToTable("IngredientNames");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            IngredientName = "Polyols"
                        },
                        new
                        {
                            IngredientId = 2,
                            IngredientName = "Salatrim"
                        },
                        new
                        {
                            IngredientId = 3,
                            IngredientName = "Alcohol"
                        },
                        new
                        {
                            IngredientId = 4,
                            IngredientName = "Organicasic"
                        },
                        new
                        {
                            IngredientId = 5,
                            IngredientName = "Fibers"
                        });
                });

            modelBuilder.Entity("Life_foods_api_csharp.Models.FoodIngredient", b =>
                {
                    b.HasOne("Life_foods_api_csharp.Models.Food", "Food")
                        .WithMany("FoodIngredients")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Life_foods_api_csharp.Models.Ingredient", "Ingredient")
                        .WithMany("FoodIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Life_foods_api_csharp.Models.Food", b =>
                {
                    b.Navigation("FoodIngredients");
                });

            modelBuilder.Entity("Life_foods_api_csharp.Models.Ingredient", b =>
                {
                    b.Navigation("FoodIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
